name: Build Ubuntu and push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'ubuntu/Dockerfile'
      - 'script/docker_build.sh'
      - '.github/workflows/build_ubuntu.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        run: |
          image=davetang/build
          ver=23.04
          script/docker_build.sh ubuntu/Dockerfile ${image} ${ver}
          docker push ${image}:${ver}
